### ISSUE TITLE
Production Build won't work on https server

### ISSUE THREAD

**Issue by Seeingred0** [60days/aframe-parcel-starter#1]
Such a lifesaver having this! Working on a project on local server, I done the build but it don't seem to want to load when using something like Netlify Drops - https://app.netlify.com/drop

Any ideas why Netlify won't take the production build from this repo?

**Comment by benferns** [comment]
Hi - thanks! I haven't touched this for a while, but something it could be is that by default parcel expects to be at the root of a domain (not sure why, always seemed like a strange choice when relative paths can be used!). 

Try adding `--public-url ./` to the package.json arguments, like this: `parcel build src/index.html --public-url ./`

If that works for you I'll probably add it to the actual repo too.

docs: https://parceljs.org/cli.html#set-the-public-url-to-serve-on

**Comment by Seeingred0** [comment]
Yes that worked! Thanks a lot!
